In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression  
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# Reading the dataset
From .csv file, using the library pandas

In [ ]:
dataset = pd.read_csv('50_Startups.csv')
print(dataset)

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

# Converting the String type label to a numeric one
This can be done with a one-hot vector too, but also with the function factorize from pandas

In [ ]:
dataset['State_Label'] = pd.factorize(dataset['State'])[0]
print(dataset)

    R&D Spend  Administration  ...     Profit State_Label
0   165349.20       136897.80  ...  192261.83           0
1   162597.70       151377.59  ...  191792.06           1
2   153441.51       101145.55  ...  191050.39           2
3   144372.41       118671.85  ...  182901.99           0
4   142107.34        91391.77  ...  166187.94           2
5   131876.90        99814.71  ...  156991.12           0
6   134615.46       147198.87  ...  156122.51           1
7   130298.13       145530.06  ...  155752.60           2
8   120542.52       148718.95  ...  152211.77           0
9   123334.88       108679.17  ...  149759.96           1
10  101913.08       110594.11  ...  146121.95           2
11  100671.96        91790.61  ...  144259.40           1
12   93863.75       127320.38  ...  141585.52           2
13   91992.39       135495.07  ...  134307.35           1
14  119943.24       156547.42  ...  132602.65           2
15  114523.61       122616.84  ...  129917.04           0
16   78013.11       121597.55  ...  126992.93           1
17   94657.16       145077.58  ...  125370.37           0
18   91749.16       114175.79  ...  124266.90           2
19   86419.70       153514.11  ...  122776.86           0
20   76253.86       113867.30  ...  118474.03           1
21   78389.47       153773.43  ...  111313.02           0
22   73994.56       122782.75  ...  110352.25           2
23   67532.53       105751.03  ...  108733.99           2
24   77044.01        99281.34  ...  108552.04           0
25   64664.71       139553.16  ...  107404.34           1
26   75328.87       144135.98  ...  105733.54           2
27   72107.60       127864.55  ...  105008.31           0
28   66051.52       182645.56  ...  103282.38           2
29   65605.48       153032.06  ...  101004.64           0
30   61994.48       115641.28  ...   99937.59           2
31   61136.38       152701.92  ...   97483.56           0
32   63408.86       129219.61  ...   97427.84           1
33   55493.95       103057.49  ...   96778.92           2
34   46426.07       157693.92  ...   96712.80           1
35   46014.02        85047.44  ...   96479.51           0
36   28663.76       127056.21  ...   90708.19           2
37   44069.95        51283.14  ...   89949.14           1
38   20229.59        65947.93  ...   81229.06           0
39   38558.51        82982.09  ...   81005.76           1
40   28754.33       118546.05  ...   78239.91           1
41   27892.92        84710.77  ...   77798.83           2
42   23640.93        96189.63  ...   71498.49           1
43   15505.73       127382.30  ...   69758.98           0
44   22177.74       154806.14  ...   65200.33           1
45    1000.23       124153.04  ...   64926.08           0
46    1315.46       115816.21  ...   49490.75           2
47       0.00       135426.92  ...   42559.73           1
48     542.05        51743.15  ...   35673.41           0
49       0.00       116983.80  ...   14681.40           1

[50 rows x 6 columns]

# Our input data is X
And it's consisted of the columns R&D Spend,Administration,Marketing Spend and State_Label

In [ ]:
data_X = pd.DataFrame(dataset,columns=['R&D Spend','Administration','Marketing Spend','State_Label'])
X = data_X.values.tolist() 
print(X)

[[165349.2, 136897.8, 471784.1, 0.0], [162597.7, 151377.59, 443898.53, 1.0], [153441.51, 101145.55, 407934.54, 2.0], [144372.41, 118671.85, 383199.62, 0.0], [142107.34, 91391.77, 366168.42, 2.0], [131876.9, 99814.71, 362861.36, 0.0], [134615.46, 147198.87, 127716.82, 1.0], [130298.13, 145530.06, 323876.68, 2.0], [120542.52, 148718.95, 311613.29, 0.0], [123334.88, 108679.17, 304981.62, 1.0], [101913.08, 110594.11, 229160.95, 2.0], [100671.96, 91790.61, 249744.55, 1.0], [93863.75, 127320.38, 249839.44, 2.0], [91992.39, 135495.07, 252664.93, 1.0], [119943.24, 156547.42, 256512.92, 2.0], [114523.61, 122616.84, 261776.23, 0.0], [78013.11, 121597.55, 264346.06, 1.0], [94657.16, 145077.58, 282574.31, 0.0], [91749.16, 114175.79, 294919.57, 2.0], [86419.7, 153514.11, 0.0, 0.0], [76253.86, 113867.3, 298664.47, 1.0], [78389.47, 153773.43, 299737.29, 0.0], [73994.56, 122782.75, 303319.26, 2.0], [67532.53, 105751.03, 304768.73, 2.0], [77044.01, 99281.34, 140574.81, 0.0], [64664.71, 139553.16, 137962.62, 1.0], [75328.87, 144135.98, 134050.07, 2.0], [72107.6, 127864.55, 353183.81, 0.0], [66051.52, 182645.56, 118148.2, 2.0], [65605.48, 153032.06, 107138.38, 0.0], [61994.48, 115641.28, 91131.24, 2.0], [61136.38, 152701.92, 88218.23, 0.0], [63408.86, 129219.61, 46085.25, 1.0], [55493.95, 103057.49, 214634.81, 2.0], [46426.07, 157693.92, 210797.67, 1.0], [46014.02, 85047.44, 205517.64, 0.0], [28663.76, 127056.21, 201126.82, 2.0], [44069.95, 51283.14, 197029.42, 1.0], [20229.59, 65947.93, 185265.1, 0.0], [38558.51, 82982.09, 174999.3, 1.0], [28754.33, 118546.05, 172795.67, 1.0], [27892.92, 84710.77, 164470.71, 2.0], [23640.93, 96189.63, 148001.11, 1.0], [15505.73, 127382.3, 35534.17, 0.0], [22177.74, 154806.14, 28334.72, 1.0], [1000.23, 124153.04, 1903.93, 0.0], [1315.46, 115816.21, 297114.46, 2.0], [0.0, 135426.92, 0.0, 1.0], [542.05, 51743.15, 0.0, 0.0], [0.0, 116983.8, 45173.06, 1.0]]

# Our labels are Y
Which represents the profit of the startup

In [ ]:
data_Y = pd.DataFrame(dataset,columns=['Profit'])
Y = data_Y.values.tolist() 
print(Y)

[[192261.83], [191792.06], [191050.39], [182901.99], [166187.94], [156991.12], [156122.51], [155752.6], [152211.77], [149759.96], [146121.95], [144259.4], [141585.52], [134307.35], [132602.65], [129917.04], [126992.93], [125370.37], [124266.9], [122776.86], [118474.03], [111313.02], [110352.25], [108733.99], [108552.04], [107404.34], [105733.54], [105008.31], [103282.38], [101004.64], [99937.59], [97483.56], [97427.84], [96778.92], [96712.8], [96479.51], [90708.19], [89949.14], [81229.06], [81005.76], [78239.91], [77798.83], [71498.49], [69758.98], [65200.33], [64926.08], [49490.75], [42559.73], [35673.41], [14681.4]]

# Getting the train and test data ready
Splitting it into 80:20 ratio

In [ ]:
X_Train,X_Test,Y_Train,Y_Test = train_test_split(X,Y,test_size=0.2,shuffle=True)

print(X_Train)
print(Y_Train)
print(X_Test)
print(Y_Test)

[[1315.46, 115816.21, 297114.46, 2.0], [131876.9, 99814.71, 362861.36, 0.0], [22177.74, 154806.14, 28334.72, 1.0], [100671.96, 91790.61, 249744.55, 1.0], [55493.95, 103057.49, 214634.81, 2.0], [142107.34, 91391.77, 366168.42, 2.0], [114523.61, 122616.84, 261776.23, 0.0], [120542.52, 148718.95, 311613.29, 0.0], [86419.7, 153514.11, 0.0, 0.0], [65605.48, 153032.06, 107138.38, 0.0], [72107.6, 127864.55, 353183.81, 0.0], [27892.92, 84710.77, 164470.71, 2.0], [153441.51, 101145.55, 407934.54, 2.0], [76253.86, 113867.3, 298664.47, 1.0], [0.0, 135426.92, 0.0, 1.0], [130298.13, 145530.06, 323876.68, 2.0], [134615.46, 147198.87, 127716.82, 1.0], [91749.16, 114175.79, 294919.57, 2.0], [144372.41, 118671.85, 383199.62, 0.0], [77044.01, 99281.34, 140574.81, 0.0], [44069.95, 51283.14, 197029.42, 1.0], [38558.51, 82982.09, 174999.3, 1.0], [46426.07, 157693.92, 210797.67, 1.0], [28754.33, 118546.05, 172795.67, 1.0], [93863.75, 127320.38, 249839.44, 2.0], [67532.53, 105751.03, 304768.73, 2.0], [0.0, 116983.8, 45173.06, 1.0], [91992.39, 135495.07, 252664.93, 1.0], [61136.38, 152701.92, 88218.23, 0.0], [75328.87, 144135.98, 134050.07, 2.0], [123334.88, 108679.17, 304981.62, 1.0], [20229.59, 65947.93, 185265.1, 0.0], [66051.52, 182645.56, 118148.2, 2.0], [64664.71, 139553.16, 137962.62, 1.0], [28663.76, 127056.21, 201126.82, 2.0], [165349.2, 136897.8, 471784.1, 0.0], [542.05, 51743.15, 0.0, 0.0], [1000.23, 124153.04, 1903.93, 0.0], [63408.86, 129219.61, 46085.25, 1.0], [101913.08, 110594.11, 229160.95, 2.0]]
[[49490.75], [156991.12], [65200.33], [144259.4], [96778.92], [166187.94], [129917.04], [152211.77], [122776.86], [101004.64], [105008.31], [77798.83], [191050.39], [118474.03], [42559.73], [155752.6], [156122.51], [124266.9], [182901.99], [108552.04], [89949.14], [81005.76], [96712.8], [78239.91], [141585.52], [108733.99], [14681.4], [134307.35], [97483.56], [105733.54], [149759.96], [81229.06], [103282.38], [107404.34], [90708.19], [192261.83], [35673.41], [64926.08], [97427.84], [146121.95]]
[[94657.16, 145077.58, 282574.31, 0.0], [23640.93, 96189.63, 148001.11, 1.0], [119943.24, 156547.42, 256512.92, 2.0], [78013.11, 121597.55, 264346.06, 1.0], [46014.02, 85047.44, 205517.64, 0.0], [73994.56, 122782.75, 303319.26, 2.0], [61994.48, 115641.28, 91131.24, 2.0], [162597.7, 151377.59, 443898.53, 1.0], [15505.73, 127382.3, 35534.17, 0.0], [78389.47, 153773.43, 299737.29, 0.0]]
[[125370.37], [71498.49], [132602.65], [126992.93], [96479.51], [110352.25], [99937.59], [191792.06], [69758.98], [111313.02]]

# Decision Tree Regressor

In [ ]:
DecisionTree = DecisionTreeRegressor(max_depth=3)
DecisionTree.fit(X_Train,Y_Train)
print(DecisionTree.score(X_Train,Y_Train))
print(DecisionTree.score(X_Test,Y_Test))

0.9696350670713659
0.8667241956659785

# Random Forest Regressor

In [ ]:
RandomForest = RandomForestRegressor(n_estimators=3)
RandomForest.fit(X_Train, Y_Train)
print(RandomForest.score(X_Train, Y_Train))
print(RandomForest.score(X_Test, Y_Test))

0.9720952878543307
0.9667135056205008

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

# Linear Regressor

In [ ]:
LinearRegress = LinearRegression()  
LinearRegress.fit(X_Train, Y_Train)

print(LinearRegress.score(X_Train, Y_Train))  
print(LinearRegress.score(X_Test, Y_Test))

0.9528204156338477
0.9285302168617353

As we can see from the results above, the Random Forest regressor gives the best results.